version: '3.1'
services:
  odoo:
    image: odoo:18.0
    env_file: .env
    depends_on:
      - psql
    ports:
      - "8069:8069" #port mapping(custom-port:8069)
    volumes:
      - data:/var/lib/odoo
      - ./:/etc/odoo
      - ./addons:/mnt/extra-addons
    entrypoint: ["/bin/bash", "-c", "odoo -u custom_product_page --without-demo=all"]

  psql:
    image: postgres:13
    env_file: .env
    volumes:
      - db:/var/lib/pgsql/data/pgdata
volumes:
  data:
  db:
# command: odoo --db_host=psql --db_user=odoo16 --db_password=odoo16 --db_name=CPP -u custom_product_page --without-demo=all

